name: First Workflow

on: 
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests and capture output
        run: |
          mkdir -p test-results
          npm test > test-results/results.txt 2>&1 || true

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results/results.txt

  deploy:
    needs: test
    runs-on: [ubuntu-latest, nodejs, staging]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # - name: Download test artifact
      #   uses: actions/download-artifact@v3
      #   with:
      #     name: test-results
      #     path: test-results/

      # - name: Display test results
      #   run: cat test-results/results.txt

      # - name: Deploy Node.js App
      #   run: |
      #     echo "Starting deployment..."
      #     npm install --production
      #     pm2 restart app.js || pm2 start app.js

      